version: "3"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      -  ./server:/app
    environment:
      - MONGOOSE_KEY=mongodb://tjdalsvndn9:skswltn123@ds235807.mlab.com:35807/docker-backend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  ngnix:
    restart: always
    build:
      context: ./ngnix
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
